### ISSUE TITLE
No way to get a query builder from ModelFactory

### ISSUE THREAD

**Issue by the-eater** [arkphp/database#5]
There is currently no way to get a queryBuilder from the modelfactory, altho desirable,  personally I think it should be something like

`$modelFactory->select($columns = '*', $alias = null)`

**Comment by ddliu** [comment]
You can always get the `QueryBuilder` from ``Connection` object:

``` php
$builder = $db->builder();
```

You can either use `QueryBuilder` to keep more control of your query, or to use `ModelFactory` to have a simple ORM API. But I don't think we should mix them together.
